modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="netherportalfix"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="netherportalfix.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[dependencies.netherportalfix]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherportalfix]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherportalfix]]
    modId="balm"
    mandatory=true
    versionRange="[${balm_version},)"
    ordering="NONE"
    side="BOTH"
