# Mod
mod_id=netherportalfix
mod_name=NetherPortalFix
mod_author = BlayTheNinth
credits = BlayTheNinth
description=Ensures correct destinations when travelling back and forth through Nether Portals in Multiplayer.
version = 26.2.0.0
group=net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/netherportalfix
sources=https://github.com/TwelveIterations/NetherPortalFix
issues=https://github.com/TwelveIterations/NetherPortalFix/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id=241160
curseforge_environments = Server
modrinth_project_id=nPZr02ET
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
neoforge_snapshot_url =
include_fabric=true
include_neoforge=false
include_forge=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
