modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="https://github.com/TwelveIterations/Balm/issues"
[[mods]]
modId="netherportalfix"
version="${version}"
displayName="${mod_name}"
displayURL="https://mods.twelveiterations.com/"
displayTest="NONE"
logoFile="netherportalfix.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "netherportalfix.mixins.json"
[[mixins]]
config = "netherportalfix.neoforge.mixins.json"
[[dependencies.netherportalfix]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.netherportalfix]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.netherportalfix]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
